//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    //не забыть добавлять картинки в ресурс через свойства после того как закинул в папку
    public partial class Demo1Entities : DbContext
    {
        private static Demo1Entities _context; //ПРОПИСАТЬ РУКАМИ
        public static Demo1Entities GetContext() //ПРОПИСАТЬ РУКАМИ
        {
            if (_context == null)
            {
                _context = new Demo1Entities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder); //ПРОПИСАТЬ РУКАМИ
        }
    
        public virtual DbSet<Партнеры> Партнеры { get; set; }
        public virtual DbSet<Продукция> Продукция { get; set; }
        public virtual DbSet<РеализацияПродуктов> РеализацияПродуктов { get; set; }
        public virtual DbSet<ТипПартнера> ТипПартнера { get; set; }
        public virtual DbSet<ТипПродукции> ТипПродукции { get; set; }
        public virtual DbSet<ТипыМатериалов> ТипыМатериалов { get; set; }
    }
}
