//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Партнеры
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Партнеры()
        {
            this.РеализацияПродуктов = new HashSet<РеализацияПродуктов>();
        }
    
        public int id_партнера { get; set; }
        public string Наименование_партнера { get; set; }
        public int id_типа_партнера { get; set; }
        public string Директор { get; set; }
        public string Электронная_почта_партнера { get; set; }
        public string Телефон_партнера { get; set; }
        public string Юридический_адрес_партнера { get; set; }
        public long ИНН { get; set; }
        public byte Рейтинг { get; set; }
        public Nullable<int> Скидка_партнера { get; set; }
    
        public virtual ТипПартнера ТипПартнера { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РеализацияПродуктов> РеализацияПродуктов { get; set; }
    }
}
