//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукция
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукция()
        {
            this.РеализацияПродуктов = new HashSet<РеализацияПродуктов>();
        }
    
        public int id_продукта { get; set; }
        public string Наименование_продукта { get; set; }
        public int Артикул { get; set; }
        public double Минимальная_стоимость_для_партнера { get; set; }
        public int id_типа_продукции { get; set; }
    
        public virtual ТипПродукции ТипПродукции { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РеализацияПродуктов> РеализацияПродуктов { get; set; }
    }
}
