//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app
{
    using System;
    using System.Collections.Generic;
    
    public partial class РеализацияПродуктов
    {
        public string id_реализации { get; set; }
        public Nullable<int> id_партнера { get; set; }
        public Nullable<int> id_продукции { get; set; }
        public Nullable<int> Количество { get; set; }
    
        public virtual Партнеры Партнеры { get; set; }
        public virtual Продукция Продукция { get; set; }
    }
}
